# Generated by Django 4.0.3 on 2022-03-17 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Name',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows', models.BooleanField(default=False)),
                ('dropdown', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Type',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
                ('Entries', models.ManyToManyField(to='testing.name')),
                ('Type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testing.type')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
